networks:
  UpsDevs:
    driver: bridge

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
    volumes:
      - db-data:/app/data
    restart: unless-stopped
    networks:
      - UpsDevs
    command: ["/app/main"]

  frontend:
    build: ./frontend
    ports:
      - "8069:8069"
    networks:
      - UpsDevs
    depends_on:
      - backend

volumes:
  db-data:


