name: Lint

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.1' 

      - name: Install Golint
        run: go install golang.org/x/lint/golint@latest

      - name: Run Gofmt
        run: gofmt -l .

      - name: Run Go Vet
        run: go vet ./...

      - name: Run Golint
        run: golint ./...
